{"name": "test_anotherone", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "def test_anotherone():\n>       assert 1 == 2\nE       assert 1 == 2\n\ntests/users/test_users.py:33: AssertionError"}, "start": 1685116595550, "stop": 1685116595551, "uuid": "710ee959-a54e-48c4-bb36-ee8e1eb9428c", "historyId": "c81199c0c1f70c3eb8a59df69b437c3a", "testCaseId": "c81199c0c1f70c3eb8a59df69b437c3a", "fullName": "tests.users.test_users#test_anotherone", "labels": [{"name": "parentSuite", "value": "tests.users"}, {"name": "suite", "value": "test_users"}, {"name": "host", "value": "dencomp"}, {"name": "thread", "value": "134936-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.users.test_users"}]}