{"name": "test_anotherone", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "def test_anotherone():\n>       assert 1 == 2\nE       assert 1 == 2\n\ntests/users/test_users.py:31: AssertionError"}, "start": 1685115589670, "stop": 1685115589670, "uuid": "4ff8e109-8203-4b60-8cc6-6cb29425f852", "historyId": "c81199c0c1f70c3eb8a59df69b437c3a", "testCaseId": "c81199c0c1f70c3eb8a59df69b437c3a", "fullName": "tests.users.test_users#test_anotherone", "labels": [{"name": "parentSuite", "value": "tests.users"}, {"name": "suite", "value": "test_users"}, {"name": "host", "value": "dencomp"}, {"name": "thread", "value": "133872-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.users.test_users"}]}