{"name": "test_anotherone", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "def test_anotherone():\n>       assert 1 == 2\nE       assert 1 == 2\n\ntests/users/test_users.py:41: AssertionError"}, "start": 1685117407411, "stop": 1685117407411, "uuid": "8e8a82c7-ea24-40b3-8063-ef823b70b437", "historyId": "c81199c0c1f70c3eb8a59df69b437c3a", "testCaseId": "c81199c0c1f70c3eb8a59df69b437c3a", "fullName": "tests.users.test_users#test_anotherone", "labels": [{"name": "parentSuite", "value": "tests.users"}, {"name": "suite", "value": "test_users"}, {"name": "host", "value": "dencomp"}, {"name": "thread", "value": "136448-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.users.test_users"}]}